/**
 * Share cards DB queries.
 * Owns: share_cards table reads/writes (create, fetch by token, increment view_count).
 * Does NOT own: token generation, route logic, analytics event firing.
 */
const { pool } = require('./index');

/**
 * Insert a new share card. Token must be pre-generated by caller.
 * Returns the inserted row.
 */
async function createShareCard({ token, streak_count, verdict_type, pattern_name, reframe_line, ref_token }) {
  const result = await pool.query(
    `INSERT INTO share_cards (token, streak_count, verdict_type, pattern_name, reframe_line, ref_token)
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING id, token, streak_count, verdict_type, pattern_name, reframe_line, ref_token, created_at, view_count`,
    [token, streak_count, verdict_type || 'HOLD', pattern_name || null, reframe_line || null, ref_token || null]
  );
  return result.rows[0];
}

/**
 * Fetch a share card by its token and atomically increment view_count.
 * Returns the row (with updated view_count) or null if not found.
 */
async function getShareCardByToken(token) {
  const result = await pool.query(
    `UPDATE share_cards
     SET view_count = view_count + 1
     WHERE token = $1
     RETURNING id, token, streak_count, verdict_type, pattern_name, reframe_line, ref_token, created_at, view_count`,
    [token]
  );
  return result.rows[0] || null;
}

module.exports = { createShareCard, getShareCardByToken };
